wsc/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('wscdatabase/', include('wscdatabase.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wscdatabase/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView


app_name = "wscdatabase"
urlpatterns = [
    path('wsc', LoginView.as_view(template_name='wsc/welcome.html'), name='wsc'),
    path('main/', views.main, name='main'),
    path('wsc/', views.welcome, name='wsc'),
    path('currentrm', views.currentrm, name='currentrm'),
    path('delete', views.delete, name='delete'),
    path('cust_info_existing', views.cust_info_existing, name='cust_info_existing'),
    path('con_info_existing', views.con_info_existing, name='con_info_existing'),
    path('newcon/', views.newcon, name='newcon'),
    path('<int:id>/dupconinfo/', views.dupconinfo, name='dupconinfo'),
    path('<int:id>/deletecust2/', views.deletecust2, name='deletecust2'),
    path('conerror', views.conerror, name='conerror'),
    path('custerror', views.custerror, name='custerror'),
    path('<int:id>/newcust/', views.newcust, name='newcust'),
    path('<int:id>/yesdupcon/', views.yesdupcon, name='yesdupcon'),
    path('<int:id>/addnewrm/', views.addnewrm, name='addnewrm'),
    path('deletecon/', views.deletecon, name='deletecon'),
    path('<int:id>/coninfo/', views.coninfo, name='coninfo'),
    path('<int:id>/custinfo/', views.custinfo, name='custinfo'),
    path('<int:id>/custinfo1/', views.custinfo1, name='custinfo1'),
    path('<int:id>/custinfo2/', views.custinfo2, name='custinfo2'),
    path('<int:id>/edit_cust_info/', views.edit_cust_info, name='edit_cust_info'),
    path('<int:id>/deletecust4/', views.deletecust4, name='deletecust4'),
    path('<int:id>/deletecust/', views.deletecust, name='deletecust'),
    path('<int:id>/deletecontractor/', views.deletecontractor, name='deletecontractor'),
    path('<int:id>/deletecon/', views.deletecon, name='deletecon'),
    path('<int:id>/prodqueue/', views.prodqueue, name='prodqueue'),

    path('<int:id>/load_rmcost1/', views.load_rmcost1, name='load_rmcost1'),
    path('<int:id>/load_rmcost2/', views.load_rmcost2, name='load_rmcost2'),
    path('<int:id>/load_rmcost3/', views.load_rmcost3, name='load_rmcost3'),
    path('<int:id>/load_rmcost4/', views.load_rmcost4, name='load_rmcost4'),
    path('<int:id>/load_rmcost5/', views.load_rmcost5, name='load_rmcost5'),
    path('<int:id>/load_rmcost6/', views.load_rmcost6, name='load_rmcost6'),
    path('<int:id>/load_rmcost7/', views.load_rmcost7, name='load_rmcost7'),
    path('<int:id>/load_rmcost8/', views.load_rmcost8, name='load_rmcost8'),
    path('<int:id>/load_rmcost9/', views.load_rmcost9, name='load_rmcost9'),
    path('<int:id>/load_rmcost10/', views.load_rmcost10, name='load_rmcost10'),
    path('<int:id>/load_rmcost11/', views.load_rmcost11, name='load_rmcost11'),
    path('<int:id>/load_rmcost12/', views.load_rmcost12, name='load_rmcost12'),
    path('<int:id>/load_rmcost13/', views.load_rmcost13, name='load_rmcost13'),

    path('<int:bid_idA>/appendcurrm/', views.appendcurrm, name='appendcurrm'),
    path('<int:id>/conedit/', views.conedit, name='conedit'),
    path('<int:id>/addnewcust/', views.addnewcust, name='addnewcust'),
    path('<int:id>/addcustconfirm/', views.addcustconfirm, name='addcustconfirm'),
    path('<int:id>/deletecustconfirm/', views.deletecustconfirm, name='deletecustconfirm'),
    path('<int:id>/deletecust3/', views.deletecust3, name='deletecust3'),
    path('<int:id>/addcust/', views.addcust, name='addcust'),

    path('<int:id>/viewnext/', views.viewnext, name='viewnext'),
    path('<int:id>/previouspage/', views.previouspage, name='previouspage'),
    path('<int:id>/bidpage/', views.bidpage, name='bidpage'),
    path('<int:id>/room/', views.room, name='room'),

    path('<int:id>/load_roomadd/', views.load_roomadd, name='load_roomadd'),

    path('<int:id>/rmmodal/', views.rmmodal, name='rmmodal'),

    path('<int:id>/cab1num/', views.cab1num, name='cab1num'),
    path('<int:id>/cab2num/', views.cab2num, name='cab2num'),
    path('<int:id>/cab3num/', views.cab3num, name='cab3num'),
    path('<int:idA>/cab4num/', views.cab4num, name='cab4num'),
    path('<int:idA>/cab5num/', views.cab5num, name='cab5num'),
    path('<int:idA>/cab6num/', views.cab6num, name='cab6num'),

    path('<int:id>/cab1/', views.cab1, name='cab1'),
    path('<int:id>/cab1A/', views.cab1A, name='cab1A'),
    path('<int:id>/deletecab1/', views.deletecab1, name='deletecab1'),

    path('<int:id>/cab2/', views.cab2, name='cab2'),
    path('<int:id>/cab2A/', views.cab2A, name='cab2A'),
    path('<int:id>/deletecab2/', views.deletecab2, name='deletecab2'),

    path('<int:id>/cab3/', views.cab3, name='cab3'),
    path('<int:id>/cab3A/', views.cab3A, name='cab3A'),
    path('<int:id>/deletecab3/', views.deletecab3, name='deletecab3'),

    path('<int:idA>/cab4/', views.cab4, name='cab4'),
    path('<int:idA>/cab4A/', views.cab4A, name='cab4A'),
    path('<int:idA>/deletecab4/', views.deletecab4, name='deletecab4'),

    path('<int:idA>/cab5/', views.cab5, name='cab5'),
    path('<int:idA>/cab5A/', views.cab5A, name='cab5A'),
    path('<int:idA>/deletecab5/', views.deletecab5, name='deletecab5'),

    path('<int:idA>/cab6/', views.cab6, name='cab6'),
    path('<int:idA>/cab6A/', views.cab6A, name='cab6A'),
    path('<int:idA>/deletecab6/', views.deletecab6, name='deletecab6'),

    path('<int:id>/cab1sides/', views.cab1sides, name='cab1sides'),
    path('<int:id>/cab1sidesA/', views.cab1sidesA, name='cab1sidesA'),

    path('<int:id>/cab2sides/', views.cab2sides, name='cab2sides'),
    path('<int:id>/cab2sidesA/', views.cab2sidesA, name='cab2sidesA'),

    path('<int:id>/cab3sides/', views.cab3sides, name='cab3sides'),
    path('<int:id>/cab3sidesA/', views.cab3sidesA, name='cab3sidesA'),

    path('<int:idA>/cab4sides/', views.cab4sides, name='cab4sides'),
    path('<int:idA>/cab4sidesA/', views.cab4sidesA, name='cab4sidesA'),

    path('<int:idA>/cab5sides/', views.cab5sides, name='cab5sides'),
    path('<int:idA>/cab5sidesA/', views.cab5sidesA, name='cab5sidesA'),

    path('<int:idA>/cab6sides/', views.cab6sides, name='cab6sides'),
    path('<int:idA>/cab6sidesA/', views.cab6sidesA, name='cab6sidesA'),

    path('<int:id>/drwer1/', views.drwer1, name='drwer1'),
    path('<int:id>/drwer1A/', views.drwer1A, name='drwer1A'),
    path('<int:id>/deletedrwer1/', views.deletedrwer1, name='deletedrwer1'),

    path('<int:id>/drwer2/', views.drwer2, name='drwer2'),
    path('<int:id>/drwer2A/', views.drwer2A, name='drwer2A'),
    path('<int:id>/deletedrwer2/', views.deletedrwer2, name='deletedrwer2'),

    path('<int:id>/drwer3/', views.drwer3, name='drwer3'),
    path('<int:id>/drwer3A/', views.drwer3A, name='drwer3A'),
    path('<int:id>/deletedrwer3/', views.deletedrwer3, name='deletedrwer3'),

    path('<int:idA>/drwer4/', views.drwer4, name='drwer4'),
    path('<int:idA>/drwer4A/', views.drwer4A, name='drwer4A'),
    path('<int:idA>/deletedrwer4/', views.deletedrwer4, name='deletedrwer4'),

    path('<int:idA>/drwer5/', views.drwer5, name='drwer5'),
    path('<int:idA>/drwer5A/', views.drwer5A, name='drwer5A'),
    path('<int:idA>/deletedrwer5/', views.deletedrwer5, name='deletedrwer5'),

    path('<int:idA>/drwer6/', views.drwer6, name='drwer6'),
    path('<int:idA>/drwer6A/', views.drwer6A, name='drwer6A'),
    path('<int:idA>/deletedrwer6/', views.deletedrwer6, name='deletedrwer6'),

    path('<int:id>/c11qty/', views.c11qty, name='c11qty'),
    path('<int:id>/c11qtyA/', views.c11qtyA, name='c11qtyA'),
    path('<int:id>/c12qty/', views.c12qty, name='c12qty'),
    path('<int:id>/c12qtyA/', views.c12qtyA, name='c12qtyA'),
    path('<int:id>/c13qty/', views.c13qty, name='c13qty'),
    path('<int:id>/c13qtyA/', views.c13qtyA, name='c13qtyA'),
    path('<int:id>/c14qty/', views.c14qty, name='c14qty'),
    path('<int:id>/c14qtyA/', views.c14qtyA, name='c14qtyA'),
    path('<int:id>/c15qty/', views.c15qty, name='c15qty'),
    path('<int:id>/c15qtyA/', views.c15qtyA, name='c15qtyA'),

    path('<int:id>/c21qty/', views.c21qty, name='c21qty'),
    path('<int:id>/c21qtyA/', views.c21qtyA, name='c21qtyA'),
    path('<int:id>/c22qty/', views.c22qty, name='c22qty'),
    path('<int:id>/c22qtyA/', views.c22qtyA, name='c22qtyA'),
    path('<int:id>/c23qty/', views.c23qty, name='c23qty'),
    path('<int:id>/c23qtyA/', views.c23qtyA, name='c23qtyA'),
    path('<int:id>/c24qty/', views.c24qty, name='c24qty'),
    path('<int:id>/c24qtyA/', views.c24qtyA, name='c24qtyA'),
    path('<int:id>/c25qty/', views.c25qty, name='c25qty'),
    path('<int:id>/c25qtyA/', views.c25qtyA, name='c25qtyA'),

    path('<int:id>/c31qty/', views.c31qty, name='c31qty'),
    path('<int:id>/c31qtyA/', views.c31qtyA, name='c31qtyA'),
    path('<int:id>/c32qty/', views.c32qty, name='c32qty'),
    path('<int:id>/c32qtyA/', views.c32qtyA, name='c32qtyA'),
    path('<int:id>/c33qty/', views.c33qty, name='c33qty'),
    path('<int:id>/c33qtyA/', views.c33qtyA, name='c33qtyA'),
    path('<int:id>/c34qty/', views.c34qty, name='c34qty'),
    path('<int:id>/c34qtyA/', views.c34qtyA, name='c34qtyA'),
    path('<int:id>/c35qty/', views.c35qty, name='c35qty'),
    path('<int:id>/c35qtyA/', views.c35qtyA, name='c35qtyA'),

    path('<int:idA>/c41qty/', views.c41qty, name='c41qty'),
    path('<int:idA>/c41qtyA/', views.c41qtyA, name='c41qtyA'),
    path('<int:idA>/c42qty/', views.c42qty, name='c42qty'),
    path('<int:idA>/c42qtyA/', views.c42qtyA, name='c42qtyA'),
    path('<int:idA>/c43qty/', views.c43qty, name='c43qty'),
    path('<int:idA>/c43qtyA/', views.c43qtyA, name='c43qtyA'),
    path('<int:idA>/c44qty/', views.c44qty, name='c44qty'),
    path('<int:idA>/c44qtyA/', views.c44qtyA, name='c44qtyA'),
    path('<int:idA>/c45qty/', views.c45qty, name='c45qty'),
    path('<int:idA>/c45qtyA/', views.c45qtyA, name='c45qtyA'),

    path('<int:idA>/c51qty/', views.c51qty, name='c51qty'),
    path('<int:idA>/c51qtyA/', views.c51qtyA, name='c51qtyA'),
    path('<int:idA>/c52qty/', views.c52qty, name='c52qty'),

wsc/views.py
from django.shortcuts import redirect


def login_redirect(request):
    return redirect('/wscdatabase/wsc')

wscdatabase/templates/wsc/addcust.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="#" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../static/login/newcust.css">
    <title>Wood Street Cabinet Bidding Program</title>
</head>
<body  style="background-image: url('../../../../img/wood.jpg');
             background-repeat: no-repeat;
             background-attachment: fixed;
             background-size: cover;">
<section id="workarea1">
            <section id="section2">
                <h1 id="formh2">Add New Customer</h1>
                <form id="form2" method="post">
                    <br>
                    {% csrf_token %}
                    {{ form.as_table }}
                    <br>
                <button id="btn1" type="submit" class="btn-success">ENTER</button>
                </form>
            </section>
        </section>
</body>
</html>
<script type="text/javascript">
</script>

wscdatabase/templates/wsc/conedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="../../../img/favicon1.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../static/login/conedit.css">
    <title>Wood Street Cabinet Bidding Program</title>
</head>
<body  style="background-image: url('../../../../img/wood.jpg');
             background-repeat: no-repeat;
             background-attachment: fixed;
             background-size: cover;">
<section id="workarea1">
    <div class="container">
        <div class="container1">
        </div>
        <div class="container2">
            <h1 id="formh2">Edit Contractor Information</h1>

                <form class="form2" method="post">
                    {% csrf_token %}
                    {{ form.name_of_field }}
                    <div class="form-rowcom">
                        {{ form.concompanytname.errors }}
                        <label id="label_concompanytname">Company:</label>
                        {{ form.concompanytname }}
                    </div>
                    <div class="form-row">
                        {{ form.confirstname.errors }}
                        <label id="label_confirstname">First Name:</label>
                        {{ form.confirstname }}
                    </div>
            <div class="form-row">
                {{ form.conlastname.errors }}
                <label id="label_conlastname">Last Name:</label>
                {{ form.conlastname }}
            </div>
            <div class="form-row">
                {{ form.conadd1.errors }}
                <label id="label_conadd1">Address #1:</label>
                {{ form.conadd1 }}
            </div>
            <div class="form-row">
                {{ form.conadd2.errors }}
                <label id="label_conadd2">Address #2:</label>
                {{ form.conadd2 }}
            </div>
            <div class="form-row">
                {{ form.concity.errors }}
                <label id="label_concity">City:</label>
                {{ form.concity }}
            </div>
            <div class="form-rowst">
                {{ form.const.errors }}
                <label class="label_const">State:</label>
                {{ form.const }}
            </div>
            <div class="form-row">
                {{ form.conzipcode.errors }}
                <label class="label_conzipcode">Zip Code:</label>
                {{ form.conzipcode }}
            </div>
            <div class="form-rowphone">
                {{ form.conwork1.errors }}
                <label class="label_conwork1">Work Phone 1:</label>
                {{ form.conwork1 }}
            </div>
            <div class="form-rowphone">
                {{ form.conwork2.errors }}
                <label class="label_conwork2">Work Phone 2:</label>
                {{ form.conwork2 }}
            </div>
            <div class="form-rowphone">
                {{ form.concell1.errors }}
                <label class="label_concell1">Cell Phone 1:</label>
                {{ form.concell1 }}
            </div>
            <div class="form-rowphone">
                 {{ form.concell2.errors }}
                 <label class="label_concell2">Cell Phone 2:</label>
                {{ form.concell2 }}
            </div>
            <div class="form-rowphone">
                {{ form.conhome.errors }}
                <label class="label_conhome">Home Phone:</label>
                {{ form.conhome }}
            </div>
            <div class="form-rowemail">
                {{ form.conemail1.errors }}
                <label class="label_conemail1">Email #1:</label>
                {{ form.conemail1 }}
            </div>
            <div class="form-rowemail">
                {{ form.conemail2.errors }}
                <label class="label_conemail2">Email #2:</label>
                {{ form.conemail2 }}
            </div>
                     <button id="btn1" type="submit" class="btn-success">ENTER</button>
            </form>


        </div>
        <div class="container3">
        </div>
    </div>
</section>
</body>
</html>
<script type="text/javascript">
</script>

wscdatabase/templates/wsc/coninfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="../../../img/favicon1.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../static/login/coninfo.css">
    <title>Wood Street Cabinet Bidding Program</title>
</head>
<body  style="background-image: url('../../../../img/wood.jpg');
             background-repeat: no-repeat;
             background-attachment: fixed;
             background-size: cover;">
    <div class="container">
        <div class="container1">
        </div>
        <div class="container2">
            <h1 id="formh2">Contractors Information</h1>
        <div class="outerdiv">
            <form class="form2" method="post">
            {% csrf_token %}
            {{ form.name_of_field }}
            <div class="form-rowcom">
                {{ form.concompanytname.errors }}
                <label id="label_concompanytname">Company:</label>
                {{ form.concompanytname }}
            </div>
            <div class="form-row">
                {{ form.confirstname.errors }}
                <label id="label_confirstname">First Name:</label>
                {{ form.confirstname }}
            </div>
            <div class="form-row">
                {{ form.conlastname.errors }}
                <label id="label_conlastname">Last Name:</label>
                {{ form.conlastname }}
            </div>
            <div class="form-row">
                {{ form.conadd1.errors }}
                <label id="label_conadd1">Address #1:</label>
                {{ form.conadd1 }}
            </div>
            <div class="form-row">
                {{ form.conadd2.errors }}
                <label id="label_conadd2">Address #2:</label>
                {{ form.conadd2 }}
            </div>
            <div class="form-row">
                {{ form.concity.errors }}
                <label id="label_concity">City:</label>
                {{ form.concity }}
            </div>
            <div class="form-rowst">
                {{ form.const.errors }}
                <label class="label_const">State:</label>
                {{ form.const }}
            </div>
            <div class="form-row">
                {{ form.conzipcode.errors }}
                <label class="label_conzipcode">Zip Code:</label>
                {{ form.conzipcode }}
            </div>
            <div class="form-rowphone">
                {{ form.conwork1.errors }}
                <label class="label_conwork1">Work Phone #1:</label>
                {{ form.conwork1 }}
            </div>
            <div class="form-rowphone">
                {{ form.conwork2.errors }}
                <label class="label_conwork2">Work Phone #2:</label>
                {{ form.conwork2 }}
            </div>
            <div class="form-rowphone">
                {{ form.concell1.errors }}
                <label class="label_concell1">Cell Phone #1:</label>
                {{ form.concell1 }}
            </div>
            <div class="form-rowphone">
                 {{ form.concell2.errors }}
                 <label class="label_concell2">Cell Phone #2:</label>
                {{ form.concell2 }}
            </div>
            <div class="form-rowphone">
                {{ form.conhome.errors }}
                <label class="label_conhome">Home Phone:</label>
                {{ form.conhome }}
            </div>
            <div class="form-rowemail">
                {{ form.conemail1.errors }}
                <label class="label_conemail1">Email #1:</label>
                {{ form.conemail1 }}
            </div>
            <div class="form-rowemail">
                {{ form.conemail2.errors }}
                <label class="label_conemail2">Email #2:</label>
                {{ form.conemail2 }}
            </div>
            </form>
        <div id="but2">
            <a class="btn btn9" id="btn1" href="../conedit">Update Contractors Info.</a>
            <a class="btn btn9" id="btn2" href="{{ instance.get_absolute36_url }}">Delete Contractor</a>
        </div>
        </div>
        </div>
        <div class="container3">
            <h1 id="formh3">Customers Information</h1>
            <a id="back"  href="{% url 'wscdatabase:con_info_existing' %}">Back</a>
            <form id="form3" method="post">
            <div id="menu2">
                <div id="header1">
                    <div id="A">ID</div>
                    <div id="C">First Name</div>
                    <div id="D">Last Name</div>
                    <div id="E">Address</div>
                    <div id="G">City</div>
                    <div id="H">St</div>
                </div>
                 <section id="sec1"></section>
                <section id="sec2"></section>
                <section id="sec3"></section>
                <section id="sec4"></section>
                <section id="sec5"></section>
                <section id="sec6"></section>
                <section id="sec7"></section>
                <section id="sec8"></section>
                <section id="sec9"></section>
                <section id="sec10"></section>
                <section id="sec11"></section>
                <section id="sec12"></section>
                <section id="sec13"></section>
                <form id="form1" method="post">
                    <div class="form-rowcustinfo">
                    {% for obj in object_list %}
                    <a id="id" href="{% url 'wscdatabase:custinfo' obj.id %}">{{ obj.id }}</a>
                    <div id="firstname">{{ obj.custfirstname }}</div>
                    <div id="lastname">{{ obj.custlastname }}</div>
                    <div id="add1">{{ obj.custadd1 }}</div>
                    <div id="city">{{ obj.custcity }}</div>
                    <div id="st">{{ obj.custst }}</div>
                    {% endfor %}
                    </div>
                </form>
            </div>
            <div id="but1">
                <a class="btn btn9" id="btn" href="{{ instance.get_absolute8_url }}">Add New Customer</a>
            </div>
            </form>
        </div>
        <div class="container4">
        </div>
    </div>
</body>
</html>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>

$(document).ready(function() {
    $("#id_idA").attr("disabled", true)
    $("#id_conid").attr("disabled", true)
    $("#id_concompanytname").attr("disabled", true)
    $("#id_confirstname").attr("disabled", true)
    $("#id_conlastname").attr("disabled", true)
    $("#id_conadd1").attr("disabled", true)
    $("#id_conadd2").attr("disabled", true)
    $("#id_concity").attr("disabled", true)
    $("#id_const").attr("disabled", true)
    $("#id_conzipcode").attr("disabled", true)
    $("#id_conwork1_0").attr("disabled", true)
    $("#id_conwork2_0").attr("disabled", true)
    $("#id_concell1_0").attr("disabled", true)
    $("#id_concell2_0").attr("disabled", true)
    $("#id_conhome_0").attr("disabled", true)
    $("#id_conemail1").attr("disabled", true)
    $("#id_conemail2").attr("disabled", true)
});

</script>

wscdatabase/templates/wsc/construction.html
{{ form.construction }}

wscdatabase/templates/wsc/currentrm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="#" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../static/login/cust_existing3.css">
    {% block head %}
    <title>Customer Search</title>
    {% endblock %}

</head>
<body  style="background-image: url('../../../../img/wood.jpg');
             background-repeat: no-repeat;
             background-attachment: fixed;
             background-size: cover;">
<section id="workarea1">
    <section id="section1">
        <h1 id="formh1">Current Room</h1>
        <a id="back"  href="{% url 'wscdatabase:main' %}">Back</a>
        <div id="menu2">
            <div id="header1">
                <div id="A">ID</div>
                <div id="C">First Name</div>
                <div id="D">Last Name</div>
                <div id="E">Address</div>
                <div id="G">City</div>
                <div id="H">St</div>
                <div id="I">Zip</div>
            </div>
            <section id="sec1"></section>
            <section id="sec2"></section>
            <section id="sec3"></section>
            <section id="sec4"></section>
            <section id="sec5"></section>
            <section id="sec6"></section>
            <section id="sec7"></section>
            <section id="sec8"></section>
            <section id="sec9"></section>
            <section id="sec10"></section>
            <section id="sec11"></section>
            <section id="sec12"></section>
            <section id="sec13"></section>
        </div>
        <form id="form1" method="post">
            <section id="sectionA" >
                {% for obj in object_list %}
                <a id="id" href="{{ obj.get_absolute16_url }}">{{ obj.bid_idA }}</a>
                <div id="firstname">{{ obj.rmnum_id }}</div>
                <div id="lastname">{{ obj.rmcost }}</div>
                <div id="add1">{{ obj.rmactive }}</div>
                <div id="city">{{ obj.rmdelete }}</div>
                {% endfor %}
            </section>
            <div id="pag" class="pagination">
                <span class="step-links">
                    {% if object_list.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ object_list.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="object_list">
                        Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                    </span>
                    {% if object_list.has_next %}
                    <a href="?page={{ object_list.next_page_number }}">next</a>
                    <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </form>
        <form id="searchbar" class="form-inline my-2 my-lg-0">
            <input name="search"
                   id="search"
                   class="form-control mr-sm-2"
                   type="search"
                   placeholder="Search Existing Customers"
                   aria-label="Search">
            <button id="searchbutton" class="btn-success" type="submit">Search</button>
        </form>
    </section>
</section>
<div class="rm-modal" style="">
    <div class="modal-content">
        <button type="button" class="button1">Open Cabinet Page for this Room</button>
        <button type="button" class="button2">Finish Selection Page</button>

    </div>
</div>
</body>

wscdatabase/templates/wsc/memo_2.html
{{ form.memo2 }}

wscdatabase/templates/wsc/memo_3.html
{{ form.memo3 }}

wscdatabase/templates/wsc/memo_5.html
{{ form.memo5 }}

wscdatabase/templates/wsc/red.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="#" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/login/red.css">
    <title>Wood Street Cabinet Bidding Program</title>
    <title>Title</title>
</head>
<body>

</body>

wscdatabase/templates/wsc/room_cost10.html
<input id="id_rmcost1010" value="{{ rmcost10.rmcost }}">
<script>
$(document).ready(function() {
    var x = document.getElementById('id_rmcost1010').value;

    if (x.indexOf("$") != 0)
    {
        x = "$" + x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }

    document.getElementById('id_rmcost1010').value = x;
    });
</script>

wscdatabase/templates/wsc/room_cost9.html
<input id="id_rmcost99" value="{{ rmcost9.rmcost }}">
<script>
$(document).ready(function() {
    var x = document.getElementById('id_rmcost99').value;

    if (x.indexOf("$") != 0)
    {
        x = "$" + x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }

    document.getElementById('id_rmcost99').value = x;
    });
</script>

wscdatabase/templates/wsc/total_perc.html
<input id="totalperc_id" value="{{ totalperc.totalperc }}">

wscdatabase/templates/wsc/wood_species.html
{{ form.woodspecies }}